# This is a basic workflow to help you get started with Actions

name: Validate Pull Request

on:
  pull_request:
    branches: [ '*' ]
    types: [opened, reopened, edited, synchronize]
    
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Branch 2
        run: |
          echo "Branch: ${{context.payload.pull_request.head.ref}}"

      - name: Validate Branch
        id: validate-branch
        uses: actions/github-script@v3
        with:
          script: |
            const branch = context.payload.pull_request.head.ref;
            core.info("Branch: " + branch);
            const branchRegExp = RegExp('^(fix|feature|test|merge)\/(AB-[0-9]+-)*([a-z0-9]+(([\-\.])?[a-z0-9]+)*)*$', 'g');
            const result = branchRegExp.exec(branch);
            if (result != null) {
              core.info("Prefix: " + result[1]);
              core.info("Anchor: " + result[2]);
              core.exportVariable("PR_BRANCH_CHECK", "success");
            }
            else {
              core.info("Branch name doesn't match required format");
              core.setOutput("result", "false");
              core.exportVariable("PR_BRANCH_CHECK", "failed");
            }

      - name: Validate Title
        id: validate-title
        uses: actions/github-script@v3
        with:
          script: |
            core.info("Pull request title: " + context.payload.pull_request.title);
            core.exportVariable("PR_TITLE_CHECK", "failed");
      
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            core.info("Input: ${{steps.validate-branch.outputs.result}}");
            if (process.env.PR_BRANCH_CHECK == "failed" || process.env.PR_TITLE_CHECK == "failed") {
              core.setFailed("Pull request doesn't meet the requirements");
            }
