# This is a basic workflow to help you get started with Actions

name: Validate Pull Request

on:
  pull_request:
    branches: [ '*' ]
    types: [opened, reopened, edited, synchronize]
    
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Branch
        uses: actions/github-script@v3
        with:
          script: |
            core.info("Branch: " + core.context.ref);
            core.exportVariable("PR_BRANCH_CHECK", "failed");

      - name: Validate Title
        uses: actions/github-script@v3
        with:
          script: |
            core.info("Pull  request title: " + context.payload.pull_request.title);
            core.exportVariable("PR_TITLE_CHECK", "failed");
      
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            if (process.env.PR_BRANCH_CHECK == "failed" || process.env.PR_TITLE_CHECK == "failed") {
              core.setFailed("Pull request doesn't meet the requirements");
            }
