# This is a basic workflow to help you get started with Actions

name: Validate Pull Request

on:
  pull_request:
    branches: [ '*' ]
    types: [opened, reopened, edited, synchronize]
    
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            core.exportVariable("checkResult", "failed");

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            core.setFailed(process.env.checkResult);
